name: documents_converter

services:
  postgres:
    build: .
    container_name: documents_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: documents_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

